### ISSUE TITLE
Special char display issue in fish-bobthefish...

### ISSUE THREAD

**Issue by jesse23** [mmis1000/Vscode-terminal-tab#4]
See snapshot below - above is terminal tab, below is terminal. Is it related to font setting? They should be using same font in my setup.

BTW vim tab bar looks OK

![image](https://user-images.githubusercontent.com/643912/103926339-c99ad600-50e6-11eb-8b7c-f6c97dc65594.png)

**Comment by jesse23** [comment]
BTW it is a very nice extension. Thanks for the work!!!

**Comment by jesse23** [comment]
As a workaround, we can set LANG='en_US.UTF8' then the issue resolved.

Also a minor side effect is in the config file, need to use escape utf8 str rather than utf8 car directly:
```
# not working in vscode-term-tab
# set -g theme_newline_prompt '➜ '
set -g theme_newline_prompt '\xE2\x9E\x9C '
```

**Comment by mmis1000** [comment]
@jesse23 how do you set the powerline font?
by setting `"editor.fontFamily"` or `"terminal.integrated.fontFamily"` ?

It seems my fault here.
I did not read the font family from correct variable.
I'd surprise that actually displayed correctly in your situation...

But the `?` is unlikely to cause by incorrect font.
What is your initial `locale` result before setting the `LANG` manually?

**Comment by jesse23** [comment]
> @jesse23 how do you set the powerline font?
> by setting `"editor.fontFamily"` or `"terminal.integrated.fontFamily"` ?
> 
> It seems my fault here.
> I did not read the font family from correct variable.
> I'd surprise that actually displayed correctly in your situation...
> 
> But the `?` is unlikely to cause by incorrect font.
> What is your initial `locale` result before setting the `LANG` manually?

Should not be a font issue but related to `LANG=`. See my post to the workaround....will close this since there is a WA.

One more thing - if we can open more xterm.js options in setting that will be great...

**Comment by mmis1000** [comment]
@jesse23 The `LANG` actually have a hard-coded default inferred from your vscode locale.
https://github.com/mmis1000/Vscode-terminal-tab/blob/8a9e5b307cfd3179c13d7846e536b47b3b1392df/src/terminalManager.ts#L122

It shouldn't be launched without a utf8 encoding locale (Which breaks your utf8 encoded rc file).

It seems the line here generated invalid locale on your system, which fallbacks to the C locale and breaks your rc file for some reason.

So I'd like to know your locale and whether you start the terminal on the same machine or remote (ssh remote, docker) for investigate what's going on here.

The vscode itself seems do a auto detect to prevent such issue, but I don't do it here.

**Comment by jesse23** [comment]
> @jesse23 The `LANG` actually have a hard-coded default inferred from your vscode locale.
> https://github.com/mmis1000/Vscode-terminal-tab/blob/8a9e5b307cfd3179c13d7846e536b47b3b1392df/src/terminalManager.ts#L122
> 
> It shouldn't be launched without a utf8 encoding locale (Which breaks your utf8 encoded rc file).
> 
> It seems the line here generated invalid locale on your system, which fallbacks to the C locale and breaks your rc file for some reason.
> 
> So I'd like to know your locale and whether you start the terminal on the same machine or remote (ssh remote, docker) for investigate what's going on here.
> 
> The vscode itself seems do a auto detect to prevent such issue, but I don't do it here.

It should be an issue related to fish shell - I tested zsh with [startship](https://starship.rs/), everything works OK.

Thanks for the clue - I will debug it later. If you don't mind I might try to contribute Pull Request later for some minor side function like key mapping. This is really a great extension that makes vscode much closer to Emacs/Vim. Thanks!

**Comment by mmis1000** [comment]
@jesse23 

That line turns out also break my vscode locale on WSL2.
I have a `locale` of `zh-TW`, but the wsl don't have anything except `en-US` by default.
The htop will displayed with such because it fallen back to the `C` locale.
![圖片](https://user-images.githubusercontent.com/2993977/104847569-c93ae000-591b-11eb-8e87-188df9e9166e.png)
Which is definitely incorrect

So I'd need need to it fix someday.

**Comment by jesse23** [comment]
Thx! Then I will re open it to track the issue.

**Comment by mmis1000** [comment]
@jesse23 
This should be fixed now.
The extension now use original `LANG` if process already have one set.
The extension now compares editor language against `locale -a` and select existing `utf-8` locale.
Also, it now supports `terminal.integrated.env.*` so you can override it if the auto detection really isn't work in specific situation (e.g. you have a weird environment that isn't utf8 locale).

**Comment by jesse23** [comment]
> @jesse23
> This should be fixed now.
> The extension now use original `LANG` if process already have one set.
> The extension now compares editor language against `locale -a` and select existing `utf-8` locale.
> Also, it now supports `terminal.integrated.env.*` so you can override it if the auto detection really isn't work in specific situation (e.g. you have a weird environment that isn't utf8 locale).

Verified. Thx!
