### ISSUE TITLE
Compatibility with Auto Dark Mode

### ISSUE THREAD

**Issue by j-f1** [mmis1000/Vscode-terminal-tab#7]
The automatic toggle in the Auto Dark Mode extension does not update the theme of the terminal (although newly opened terminals will look ok)

> Name: Auto Dark Mode
> Id: linusu.auto-dark-mode
> Description: 
> Version: 0.1.7
> Publisher: LinusU
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=LinusU.auto-dark-mode

**Comment by mmis1000** [comment]
It's a bug, I didn't register the theme change event at all.
